name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Workflow-level environment variables (available to all jobs/steps)
env:
  CUSTOM_VAR: "hello-from-workflow"

jobs:
  build:
    runs-on: ubuntu-latest   # or macos-latest

    steps:
      # A) Checkout
      - name: Check out code
        uses: actions/checkout@v4

      # B) Node setup + npm cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      # C) Show the env var (demo)
      - name: Show env var
        run: echo "CUSTOM_VAR is $CUSTOM_VAR"

      # D) Install
      - name: Install dependencies
        run: npm ci

      # E) Conditional build (only on push to main)
      - name: Build (only on push to main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npm run build

      # F) Tests (always run)
      - name: Run tests
        run: npm test

      # G) Produce an output for next step (modern way)
      - id: compute
        name: Compute value
        run: |
         echo "value=hello-from-step-one" >> "$GITHUB_OUTPUT"

      # H) Consume the output
      - name: Use previous step output
        run: |
          echo "Received: ${{ steps.compute.outputs.value }}"


     # I) Use a secret (safe demo)
      #    NOTE: 'if:' checks env.ACCESS_TOKEN, not secrets.ACCESS_TOKEN
      - name: Use secret (safe demo)
        if: ${{ env.ACCESS_TOKEN != '' }}   # <-- this is allowed
        run: |
          # ACCESS_TOKEN is already available from the job-level env above
          echo "Secret length is ${#ACCESS_TOKEN}"
          # Example (don't print the token):
          # curl -H "Authorization: Bearer $ACCESS_TOKEN" https://api.example.com/me